---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |>
  rename(latitude = lat, longitude = long) |>
  select(
    borough = neighbourhood_group, neighbourhood, stars, price, room_type,
    latitude, longitude) |>
  drop_na(stars)
```



Column {.sidebar}
-----------------------------------------------------------------------

```{r}
boroughs=nyc_airbnb |> distinct(borough) |> pull()



selectInput(
  inputId = "borough_choice",
  label = h3("Select Borough"),
  choices = boroughs,
  selected = "Manhattan",
)
```

```{r}

min_price=nyc_airbnb|> pull(price)|>min()
max_price=nyc_airbnb|> pull(price)|>max()

sliderInput(
  inputId = "price_choice",
  label=h3("Choose a price range"),
  min=min_price,
  max=max_price,
  value=c(200,400),
)
```

```{r}

rooms=nyc_airbnb |> distinct(room_type) |> pull()

radioButtons(
  inputId = "room_choice",
  label = h3("Select a room type"),
  choices= rooms,
  selected = "Private room",
)

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

renderPlotly(
  nyc_airbnb|>
    filter(borough==input[["borough_choice"]],
           price <= input[["price_choice"]][2],
  price >= input[["price_choice"]][1],
room_type==input[["room_choice"]]) |>
    plot_ly(
      x=~longitude,y=~latitude, color=~price,
      type="scatter", mode="markers"
    )
)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

renderPlotly(
  nyc_airbnb|>
        filter(borough==input[["borough_choice"]],
           price <= input[["price_choice"]][2],
  price >= input[["price_choice"]][1],
room_type==input[["room_choice"]]) |>
count(neighbourhood)|>
  mutate(neighbourhood=fct_reorder(neighbourhood,n))|>
  plot_ly(x=~neighbourhood, y=~n, type= "bar")
)


```

### Chart C

```{r}

renderPlotly(
  nyc_airbnb|>
    mutate(neighbourhood=fct_reorder(neighbourhood, price))|>
    plot_ly(x=~neighbourhood,y=~price, type="box")
)
```

